### ISSUE TITLE
overlay status

### ISSUE THREAD

**Issue by hasufell** [gentoo/python#1]
Is this overlay dead?

**Comment by mgorny** [comment]
Yes.

**Comment by hasufell** [comment]
Revive or delete please. The overlay name is too valuable to lock it.

**Comment by mgorny** [comment]
And yet it is too valuable to allow some random overlays to take it :P.

**Comment by mgorny** [comment]
@floppym, what do you think?

**Comment by hasufell** [comment]
So if no one jumps in, I'll delete this in a few weeks.

**Comment by mgorny** [comment]
So what do you want to put here instead?

**Comment by floppym** [comment]
Let's just leave it here in case someone wants to use it in the future.

**Comment by mrueg** [comment]
I agree with floppym and mgorny here. Though we should update the README so it matches the overlay status as "inactive"?

**Comment by floppym** [comment]
I think it is fairly obvious that it is inactive based on the commit log. However, we could add a message asking to contact the python team if someone wants to use it.

**Comment by mgorny** [comment]
Resurrected.
